spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/aluraflix}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: ${DATABASE_DRIVER_CLASS_NAME:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: ${DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}